services:
  nginx:
    container_name: nginx
    image: nginx:1.24
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.da/tls:/etc/nginx/tls
    ports:
      - 443:443
  backend:
    container_name: backend
    init: true
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ../images/user-icon:/node/images/user-icon
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
    ports:
      - 33060:3306
    volumes:
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      - ../volume/mysql:/var/lib/mysql
      - ./mysql/mysql_migration:/etc/mysql/mysql_migration
      - ./mysql/mysql.conf:/etc/mysql/conf.d/mysql.cnf
  datadog-agent:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    pid: host
    environment:
      - DD_API_KEY=2aede3e1907dbcad3842460d75e37830
      - DD_SITE=ap1.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
